### ISSUE TITLE
sbb.ch shows more trains than ojp-js

### ISSUE THREAD

**Issue by iKK001** [openTdataCH/ojp-js#39]
I observed that sbb.ch website shows more trains than the ojp-js library:

Esample: Lugano to Luzern from the SBB.ch website:

![sbb](https://github.com/openTdataCH/ojp-js/assets/8404556/b86ceb9e-d342-469d-9ef6-22b344ac0338)

Same tripRequest query with ojp-js library:

![Screenshot 2024-01-06 at 12 33 06](https://github.com/openTdataCH/ojp-js/assets/8404556/cfe914be-c76b-47b8-9d47-053cd0cfa0e6)

The 14:30 connection is clearly missing.

This can be repeated with many other connections....

Any idea why ??

------ 

After some more investigation, I observe that SBB.ch delivers connections wheras ojp-js - for certain cases - does not!

For example

Connection from "Chiasso" (id = 8505307) to "Basel, Holee" (id = 8589328)

Here what SBB.ch delivers...

![Screenshot 2024-01-06 at 18 05 09](https://github.com/openTdataCH/ojp-js/assets/8404556/a9e9e958-614a-48bd-b251-c95953042b63)

And here what ojp-js delivers (i.e. no trips !!!!!!...)

![Screenshot 2024-01-06 at 18 04 53](https://github.com/openTdataCH/ojp-js/assets/8404556/092cca96-a53a-4a3e-bbeb-27d3f2ca200d)

 Any idea why the difference ?

**Comment by vasile** [comment]
Thanks for reporting @iKK001 - It seems that `ojp:Trip/ojp:Distance` node was the issue, the SDK was expecting that to be present but is not always the case, is optional, I have patched it in case of missing to compute it from `LegSection` from the indvidual nodes
